-- Datos de demostración de Guardian.
--
-- GENERADO por scripts/generar-seed-sql.ts a partir de src/lib/data/seed.ts.
-- No editar a mano: se pisa en la próxima corrida.
--
-- Las cifras económicas son demostrativas, no salen de ningún contrato firmado.

-- Se vacía antes de cargar, así correrlo dos veces no duplica nada.
truncate table
  auditoria, liquidaciones, movimientos_bancarios, aportes, discrepancias,
  extracciones, documentos, identificadores, seguimiento, fideicomisos,
  restricciones, controles, cronograma_hitos, presupuesto_rubros, contingencias,
  comisiones, condiciones_economicas, proyectos, garantias, colaboradores,
  productores, perfiles
restart identity cascade;

insert into productores (id, nombre, razon_social, responsable, correo, telefono, cuit, renspa, marca_registrada, establecimiento, localidad, provincia, sistema_productivo, capacidad_instalada, ocupacion_actual, ciclos_completados) values
  ('prod-1', 'Tropa Agroganadera', 'TROPA AGROGANADERA S.A.', 'Marcelo Giraudo', 'marcelo@tropaagro.com.ar', '2494 55-6677', '30-71903430-2', '01.036.0.01532/04', 'TA-4471', 'DOÑA INA', 'Chenaut, Exaltación de la Cruz', 'Buenos Aires', 'corral', 1200, 760, 4),
  ('prod-2', 'La Redención', 'LA REDENCIÓN S.R.L.', 'Silvina Ferreyra', 'silvina@laredencion.com.ar', '3472 41-9080', '30-70912844-7', '02.017.0.00841/11', 'LR-0912', 'LA REDENCIÓN', 'Marcos Juárez', 'Córdoba', 'mixto', 800, 310, 1),
  ('prod-3', 'El Amanecer', 'GANADERA EL AMANECER S.A.', 'Hugo Brambilla', 'hugo@elamanecer.com.ar', '3462 30-1144', '30-71554098-5', '03.084.0.02219/07', 'EA-2219', 'EL AMANECER', 'Venado Tuerto', 'Santa Fe', 'pastura', 600, 540, 2);

insert into colaboradores (id, nombre, email, telefono, cuil, alta_at, identidad_metodo, identidad_fecha, cbu_devolucion, alias_devolucion) values
  ('col-1', 'Lucía Ferreyra', 'lucia.ferreyra@ejemplo.com.ar', '+54 9 11 5544-2210', '27-33845120-4', '2026-07-14', 'DNI contra RENAPER', '2026-07-15', '0000000000000000000000', 'lucia.ferreyra.gdn'),
  ('col-otros', 'Resto de los colaboradores', 'colaboradores@ejemplo.com.ar', '—', '—', '2026-01-01', null, null, '', '');

insert into garantias (id, productor_id, tipo, identificacion, descripcion, valuacion_ars, cupo_proyectos, vigencia_hasta, estado, estado_constitucion, instrumento) values
  ('gar-1', 'prod-1', 'hipoteca', 'Matrícula 12.847 — Partido de Rojas', 'Primera hipoteca sobre 180 hectáreas del establecimiento, constituida a favor del fideicomiso marco.', 630000000, 2, '2028-03-31', 'vigente', 'constituida', 'Escritura inscripta en el registro que corresponde (dato demostrativo)'),
  ('gar-2', 'prod-1', 'prenda_rodeo', 'Registro prendario 4.192/25', 'Prenda sobre las cabezas identificadas por caravana en el listado RFID de cada proyecto.', 144000000, 2, '2026-12-31', 'vigente', 'constituida', 'Escritura inscripta en el registro que corresponde (dato demostrativo)'),
  ('gar-3', 'prod-1', 'aval_establecimiento', 'Aval La Josefina Agropecuaria S.A.', 'La sociedad del grupo responde con su patrimonio por el incumplimiento del productor.', 225000000, 2, '2027-06-30', 'vigente', 'constituida', 'Escritura inscripta en el registro que corresponde (dato demostrativo)'),
  ('gar-4', 'prod-2', 'hipoteca', 'Matrícula 3.508 — Partido de Bolívar', 'Hipoteca en segundo grado sobre el casco del establecimiento.', 315000000, 2, '2027-09-30', 'vigente', 'constituida', 'Escritura inscripta en el registro que corresponde (dato demostrativo)'),
  ('gar-5', 'prod-3', 'cesion_derechos', 'Cesión 2025/14 — Frigorífico Gorina', 'Lo que el frigorífico paga por el lote se cobra directo en el fideicomiso, antes de pasar por el productor.', 117000000, 1, '2026-08-31', 'sin_verificar', 'propuesta', null);

insert into proyectos (id, productor_id, titulo, modalidad, motivo_revision_modalidad, destino_detalle, tipo_posesion, sistema_productivo, cabezas, categoria, destino_fondos_previo, raza, peso_entrada_kg, peso_salida_objetivo_kg, monto_objetivo_ars, monto_recaudado_ars, monto_liberado_ars, monto_retirado_ars, monto_minimo_inicio_ars, plazo_dias, plazo_cobro_dias, rendimiento_esperado_pct, garantia_id, tiene_seguro, estado, provincia, creado_at, publicado_at, resultado_dte_salida, resultado_cabezas_faena, resultado_kilos_vivos, resultado_kg_carne, resultado_rendimiento_pct, resultado_fecha) values
  ('pry-1', 'prod-1', 'Engorde a corral — 180 novillitos', 'capital_trabajo', null, 'Ración balanceada de los 120 días, plan sanitario y mano de obra del corral. La hacienda ya es del establecimiento.', 'existencia_comprobada', 'corral', 180, 'Novillito', 'capital_trabajo', 'Angus', 250, 390, 86850000, 52950000, 20700000, 20700000, 52050000, 120, 15, 34, 'gar-1', true, 'abierto', 'Buenos Aires', '2026-08-14', '2026-08-21', null, null, null, null, null, null),
  ('pry-2', 'prod-2', 'Compra e invernada — 220 terneros', 'compra_engorde', null, 'Compra de los 220 terneros. El campo, la pastura y el trabajo los pone el establecimiento.', 'promesa_inversion', 'mixto', 220, 'Ternero', 'ciclo_engorde', 'Braford', 190, 330, 116400000, 23250000, 0, 0, 69900000, 180, 30, 41, 'gar-4', true, 'abierto', 'Córdoba', '2026-09-02', '2026-09-09', null, null, null, null, null, null),
  ('pry-3', 'prod-3', 'Recría sobre pastura — 140 vaquillonas', 'compra_engorde', null, 'Compra de 60 vaquillonas y suplementación proteica de todo el lote sobre pastura.', 'hibrido', 'pastura', 140, 'Vaquillona', 'mixto', 'Angus colorado', 210, 340, 65100000, 65100000, 0, 0, 39000000, 150, 30, 29, 'gar-5', false, 'fondeado', 'Santa Fe', '2026-07-28', '2026-08-04', null, null, null, null, null, null),
  ('pry-4', 'prod-1', 'Engorde a corral — 200 vaquillonas', 'capital_trabajo', null, 'Ración, sanidad y mano de obra del ciclo. Los animales ya están en el corral.', 'existencia_comprobada', 'corral', 200, 'Vaquillona', 'capital_trabajo', 'Angus', 240, 380, 99300000, 0, 0, 0, 59550000, 120, 15, 33, 'gar-2', true, 'en_validacion', 'Buenos Aires', '2026-09-18', null, null, null, null, null, null, null),
  ('pry-5', 'prod-2', 'Terminación a corral — 95 novillos', 'capital_trabajo', null, 'Alimento de terminación, sanidad y flete a faena.', 'existencia_comprobada', 'corral', 95, 'Novillo', 'capital_trabajo', 'Hereford', 320, 450, 49200000, 0, 0, 0, null, 90, 15, 26, 'gar-4', true, 'en_validacion', 'Córdoba', '2026-09-20', null, null, null, null, null, null, null),
  ('pry-6', 'prod-1', 'Engorde a corral — 28 cabezas (ciclo cerrado)', 'capital_trabajo', null, 'Ración y sanidad del ciclo.', 'existencia_comprobada', 'corral', 28, 'Vaquillona / Novillito', 'capital_trabajo', 'Angus', 240, 330, 13500000, 13500000, 13500000, 9300000, 8100000, 110, 15, 31, 'gar-3', true, 'cerrado', 'Buenos Aires', '2026-05-30', '2026-06-04', '32624494', 28, 9240, 5437, 58.84, '2026-09-21'),
  ('pry-7', 'prod-3', 'Invernada sobre pastura — 60 terneras', 'compra_engorde', null, 'Compra de las 60 terneras a la consignataria.', 'promesa_inversion', 'pastura', 60, 'Ternera', 'ciclo_engorde', 'Brangus', 180, 300, 29850000, 0, 0, 0, null, 180, 30, 38, null, false, 'borrador', 'Santa Fe', '2026-09-22', null, null, null, null, null, null, null),
  ('pry-8', 'prod-1', 'Recría a corral — 90 terneras', 'capital_trabajo', null, '', 'existencia_comprobada', 'corral', 90, 'Ternera', 'capital_trabajo', 'Cruza británica', 190, 0, 0, 0, 0, 0, null, 150, 15, 0, null, false, 'borrador', 'Buenos Aires', '2026-09-24', null, null, null, null, null, null, null),
  ('pry-14', 'prod-1', 'Ciclo 2026 — 110 novillitos', null, 'El proyecto venía cargado como mixto y el detalle no dice si el capital compra hacienda o solo financia los gastos del lote que ya está en el corral. Hasta saberlo no se puede decir si el colaborador participa del resultado o cobra una tasa.', 'Capital para el ciclo 2026 del lote de novillitos.', 'hibrido', 'corral', 110, 'Novillito', 'mixto', 'Cruza británica', 230, 370, 57000000, 0, 0, 0, null, 140, null, 0, null, false, 'borrador', 'Buenos Aires', '2026-09-26', null, null, null, null, null, null, null),
  ('pry-9', 'prod-1', 'Terminación a corral — 120 novillos', 'capital_trabajo', null, 'Ración, sanidad y mano de obra de los 150 días de encierre.', 'existencia_comprobada', 'corral', 120, 'Novillo', 'capital_trabajo', 'Angus', 310, 440, 64500000, 64500000, 43050000, 32100000, 38700000, 90, 15, 28, 'gar-2', true, 'en_curso', 'Buenos Aires', '2026-07-02', '2026-07-09', null, null, null, null, null, null),
  ('pry-10', 'prod-1', 'Engorde a corral — 150 novillitos (ciclo 2025/26)', 'capital_trabajo', null, 'Ración y sanidad del ciclo.', 'existencia_comprobada', 'corral', 150, 'Novillito', 'capital_trabajo', 'Angus', 245, 385, 71400000, 71400000, 71400000, 71400000, 42900000, 115, 15, 32, 'gar-3', true, 'cerrado', 'Buenos Aires', '2026-01-16', '2026-01-23', '31488207', 150, 57450, 33218, 57.82, '2026-05-19'),
  ('pry-11', 'prod-1', 'Recría a corral — 95 vaquillonas (ciclo 2025)', 'capital_trabajo', null, 'Ración, sanidad y mano de obra del ciclo.', 'existencia_comprobada', 'corral', 95, 'Vaquillona', 'capital_trabajo', 'Hereford', 200, 320, 39300000, 39300000, 39300000, 39300000, 23550000, 130, 15, 29, 'gar-1', true, 'cerrado', 'Buenos Aires', '2025-07-04', '2025-07-11', '30117645', 95, 30115, 17285, 57.4, '2025-11-28'),
  ('pry-12', 'prod-1', 'Engorde a corral — 60 novillitos (primer ciclo)', 'capital_trabajo', null, 'Ración y sanidad del ciclo.', 'existencia_comprobada', 'corral', 60, 'Novillito', 'capital_trabajo', 'Angus', 255, 375, 25500000, 25500000, 25500000, 25500000, 15300000, 105, 15, 27, 'gar-2', true, 'cerrado', 'Buenos Aires', '2025-02-10', '2025-02-18', '29004318', 60, 19380, 11066, 57.1, '2025-06-03'),
  ('pry-13', 'prod-1', 'Ración y sanidad — 210 novillitos en engorde', 'capital_trabajo', null, 'Solo insumos: ración balanceada de los 135 días, plan sanitario completo, sales minerales y la mano de obra del corral. Los 210 novillitos ya son del establecimiento y están encerrados; el capital no compra un solo animal.', 'existencia_comprobada', 'corral', 210, 'Novillito', 'capital_trabajo', 'Braford', 240, 400, 62250000, 18600000, 0, 0, 37350000, 135, 15, 29, 'gar-1', false, 'abierto', 'Buenos Aires', '2026-09-10', '2026-09-20', null, null, null, null, null, null);

insert into condiciones_economicas (proyecto_id, version, participacion_colaboradores_pct, participacion_productor_pct, participacion_base, participacion_fuente, tasa_pct, tasa_base, tasa_calculo, tasa_vencimientos, tasa_fuente, proyeccion_fecha, proyeccion_supuestos, proyeccion_ingresos_estimados_ars, proyeccion_costos_estimados_ars, proyeccion_comisiones_estimadas_ars) values
  ('pry-1', 1, null, null, null, null, 34, 'ciclo', 'Sobre el capital aportado, devengado a lo largo del ciclo y sin capitalización', 'Un único vencimiento al cierre del ciclo, a los 120 días', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-2', 1, 65, 35, 'Sobre el resultado neto de la venta, una vez cubiertos los gastos reconocidos del ciclo', 'demostrativo', null, null, null, null, null, '2026-09-01', '["Precio del kilo vivo al cierre igual al de la última semana","Sin mortandad por encima de la prevista en el contrato","Gastos del ciclo dentro del presupuesto aprobado"]'::jsonb, 164124000, 116400000, null),
  ('pry-3', 1, 65, 35, 'Sobre el resultado neto de la venta, una vez cubiertos los gastos reconocidos del ciclo', 'demostrativo', null, null, null, null, null, '2026-09-01', '["Precio del kilo vivo al cierre igual al de la última semana","Sin mortandad por encima de la prevista en el contrato","Gastos del ciclo dentro del presupuesto aprobado"]'::jsonb, 83979000, 65100000, null),
  ('pry-4', 1, null, null, null, null, 33, 'ciclo', 'Sobre el capital aportado, devengado a lo largo del ciclo y sin capitalización', 'Un único vencimiento al cierre del ciclo, a los 120 días', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-5', 1, null, null, null, null, null, null, 'Sin pactar', 'Sin pactar', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-6', 1, null, null, null, null, 31, 'ciclo', 'Sobre el capital aportado, devengado a lo largo del ciclo y sin capitalización', 'Un único vencimiento al cierre del ciclo, a los 110 días', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-7', 1, null, null, 'Sin pactar', 'demostrativo', null, null, null, null, null, null, '[]'::jsonb, null, null, null),
  ('pry-8', 1, null, null, null, null, null, null, 'Sin pactar', 'Sin pactar', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-14', 1, null, null, null, null, null, null, null, null, null, null, '[]'::jsonb, null, null, null),
  ('pry-9', 1, null, null, null, null, 28, 'ciclo', 'Sobre el capital aportado, devengado a lo largo del ciclo y sin capitalización', 'Un único vencimiento al cierre del ciclo, a los 90 días', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-10', 1, null, null, null, null, 32, 'ciclo', 'Sobre el capital aportado, devengado a lo largo del ciclo y sin capitalización', 'Un único vencimiento al cierre del ciclo, a los 115 días', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-11', 1, null, null, null, null, 29, 'ciclo', 'Sobre el capital aportado, devengado a lo largo del ciclo y sin capitalización', 'Un único vencimiento al cierre del ciclo, a los 130 días', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-12', 1, null, null, null, null, 27, 'ciclo', 'Sobre el capital aportado, devengado a lo largo del ciclo y sin capitalización', 'Un único vencimiento al cierre del ciclo, a los 105 días', 'demostrativo', null, '[]'::jsonb, null, null, null),
  ('pry-13', 1, null, null, null, null, 29, 'ciclo', 'Sobre el capital aportado, devengado a lo largo del ciclo y sin capitalización', 'Un único vencimiento al cierre del ciclo, a los 135 días', 'demostrativo', null, '[]'::jsonb, null, null, null);

insert into comisiones (proyecto_id, concepto, base, porcentaje, a_cargo_de, momento, fuente, orden) values
  ('pry-1', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-1', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-1', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-2', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-2', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-2', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-2', 'Comisión de éxito', 'Sobre el resultado neto, después de gastos reconocidos', 2, 'fideicomiso', 'Solo si el resultado es positivo', 'demostrativo', 3),
  ('pry-3', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-3', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-3', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-3', 'Comisión de éxito', 'Sobre el resultado neto, después de gastos reconocidos', 2, 'fideicomiso', 'Solo si el resultado es positivo', 'demostrativo', 3),
  ('pry-4', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-4', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-4', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-5', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-5', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-5', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-6', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-6', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-6', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-7', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-7', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-7', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-7', 'Comisión de éxito', 'Sobre el resultado neto, después de gastos reconocidos', 2, 'fideicomiso', 'Solo si el resultado es positivo', 'demostrativo', 3),
  ('pry-8', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-8', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-8', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-14', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-14', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-14', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-9', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-9', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-9', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-10', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-10', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-10', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-11', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-11', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-11', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-12', 'Comisión de colocación', 'Sobre el capital efectivamente acreditado', 3, 'fideicomiso', 'Al liberarse el primer desembolso', 'demostrativo', 0),
  ('pry-12', 'Monitoreo del ciclo', 'Sobre el capital acreditado, por el plazo del ciclo', 1, 'fideicomiso', 'Prorrateado, se descuenta en la liquidación', 'demostrativo', 1),
  ('pry-12', 'Honorarios del fiduciario', 'Sobre el capital administrado', 1.5, 'fideicomiso', 'En la liquidación del ciclo', 'demostrativo', 2),
  ('pry-13', 'Comisión de colocación', 'Sin definir', null, 'fideicomiso', 'Sin definir', 'demostrativo', 0);

insert into contingencias (proyecto_id, caso, que_dice, a_cargo_de, fuente, orden) values
  ('pry-1', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-1', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-1', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-1', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-2', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-2', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-2', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-2', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-2', 'precio', 'El resultado depende del precio de la hacienda al cierre. Puede ser menor al proyectado, y puede ser negativo: el colaborador participa de lo que se obtenga.', 'El colaborador, en proporción a lo aportado', 'demostrativo', 4),
  ('pry-3', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-3', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-3', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-3', 'incumplimiento', 'No hay garantía constituida en este proyecto: el reclamo es contra el productor y no hay un bien afectado para ejecutar.', 'El productor', 'demostrativo', 3),
  ('pry-3', 'precio', 'El resultado depende del precio de la hacienda al cierre. Puede ser menor al proyectado, y puede ser negativo: el colaborador participa de lo que se obtenga.', 'El colaborador, en proporción a lo aportado', 'demostrativo', 4),
  ('pry-4', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-4', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-4', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-4', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-5', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-5', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-5', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-5', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-6', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-6', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-6', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-6', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-7', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-7', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-7', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-7', 'incumplimiento', 'No hay garantía constituida en este proyecto: el reclamo es contra el productor y no hay un bien afectado para ejecutar.', 'El productor', 'demostrativo', 3),
  ('pry-7', 'precio', 'El resultado depende del precio de la hacienda al cierre. Puede ser menor al proyectado, y puede ser negativo: el colaborador participa de lo que se obtenga.', 'El colaborador, en proporción a lo aportado', 'demostrativo', 4),
  ('pry-8', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-8', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-8', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-8', 'incumplimiento', 'No hay garantía constituida en este proyecto: el reclamo es contra el productor y no hay un bien afectado para ejecutar.', 'El productor', 'demostrativo', 3),
  ('pry-14', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-14', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-14', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-14', 'incumplimiento', 'No hay garantía constituida en este proyecto: el reclamo es contra el productor y no hay un bien afectado para ejecutar.', 'El productor', 'demostrativo', 3),
  ('pry-9', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-9', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-9', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-9', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-10', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-10', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-10', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-10', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-11', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-11', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-11', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-11', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-12', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-12', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-12', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-12', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3),
  ('pry-13', 'mortandad', 'Hasta el 2 % del lote lo absorbe el fideicomiso. Por encima de ese piso responde el productor, salvo caso fortuito acreditado.', 'Fideicomiso hasta el piso; después, el productor', 'demostrativo', 0),
  ('pry-13', 'sanitaria', 'El productor avisa dentro de las 48 horas, aísla el lote y carga el diagnóstico. El tratamiento sale del rubro de sanidad del presupuesto aprobado.', 'Presupuesto del proyecto', 'demostrativo', 1),
  ('pry-13', 'demora', 'El ciclo puede estirarse hasta 30 días sin que cambien las condiciones. Más allá de eso, se avisa a los colaboradores y se revisa el plazo de cobro.', 'Sin costo para el colaborador dentro de los 30 días', 'demostrativo', 2),
  ('pry-13', 'incumplimiento', 'Se intima al productor y, si no regulariza, el fiduciario ejecuta la garantía constituida.', 'El productor, con su garantía afectada', 'demostrativo', 3);

insert into presupuesto_rubros (proyecto_id, rubro, concepto, proveedor, monto_ars, periodo, orden) values
  ('pry-1', 'Alimentación', 'Ración diaria del lote', null, 53847000, 'Los 120 días del ciclo', 0),
  ('pry-1', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 12159000, 'Los 120 días del ciclo', 1),
  ('pry-1', 'Corral', 'Alquiler del corral y servicios', null, 13896000, 'Los 120 días del ciclo', 2),
  ('pry-1', 'Flete', 'Traslados del ciclo', null, 6948000, 'Los 120 días del ciclo', 3),
  ('pry-2', 'Hacienda', 'Compra de 220 cabezas de ternero, 190 kg de entrada', null, 79152000, 'Al inicio', 0),
  ('pry-2', 'Alimentación', 'Ración de recría y terminación', null, 25608000, 'Los 180 días del ciclo', 1),
  ('pry-2', 'Sanidad', 'Plan sanitario del lote', null, 5820000, 'Los 180 días del ciclo', 2),
  ('pry-2', 'Flete', 'Traslado al establecimiento receptor', null, 5820000, 'Al inicio', 3),
  ('pry-3', 'Hacienda', 'Compra de 140 cabezas de vaquillona, 210 kg de entrada', null, 44268000, 'Al inicio', 0),
  ('pry-3', 'Alimentación', 'Ración de recría y terminación', null, 14322000, 'Los 150 días del ciclo', 1),
  ('pry-3', 'Sanidad', 'Plan sanitario del lote', null, 3255000, 'Los 150 días del ciclo', 2),
  ('pry-3', 'Flete', 'Traslado al establecimiento receptor', null, 3255000, 'Al inicio', 3),
  ('pry-4', 'Alimentación', 'Ración diaria del lote', null, 61566000, 'Los 120 días del ciclo', 0),
  ('pry-4', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 13902000, 'Los 120 días del ciclo', 1),
  ('pry-4', 'Corral', 'Alquiler del corral y servicios', null, 15888000, 'Los 120 días del ciclo', 2),
  ('pry-4', 'Flete', 'Traslados del ciclo', null, 7944000, 'Los 120 días del ciclo', 3),
  ('pry-5', 'Alimentación', 'Ración diaria del lote', null, 30504000, 'Los 90 días del ciclo', 0),
  ('pry-5', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 6888000, 'Los 90 días del ciclo', 1),
  ('pry-5', 'Corral', 'Alquiler del corral y servicios', null, 7872000, 'Los 90 días del ciclo', 2),
  ('pry-5', 'Flete', 'Traslados del ciclo', null, 3936000, 'Los 90 días del ciclo', 3),
  ('pry-6', 'Alimentación', 'Ración diaria del lote', null, 8370000, 'Los 110 días del ciclo', 0),
  ('pry-6', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 1890000, 'Los 110 días del ciclo', 1),
  ('pry-6', 'Corral', 'Alquiler del corral y servicios', null, 2160000, 'Los 110 días del ciclo', 2),
  ('pry-6', 'Flete', 'Traslados del ciclo', null, 1080000, 'Los 110 días del ciclo', 3),
  ('pry-7', 'Hacienda', 'Compra de 60 cabezas de ternera, 180 kg de entrada', null, 20298000, 'Al inicio', 0),
  ('pry-7', 'Alimentación', 'Ración de recría y terminación', null, 6567000, 'Los 180 días del ciclo', 1),
  ('pry-7', 'Sanidad', 'Plan sanitario del lote', null, 1492500, 'Los 180 días del ciclo', 2),
  ('pry-7', 'Flete', 'Traslado al establecimiento receptor', null, 1492500, 'Al inicio', 3),
  ('pry-14', 'Alimentación', 'Ración diaria del lote', null, 35340000, 'Los 140 días del ciclo', 0),
  ('pry-14', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 7980000, 'Los 140 días del ciclo', 1),
  ('pry-14', 'Corral', 'Alquiler del corral y servicios', null, 9120000, 'Los 140 días del ciclo', 2),
  ('pry-14', 'Flete', 'Traslados del ciclo', null, 4560000, 'Los 140 días del ciclo', 3),
  ('pry-9', 'Alimentación', 'Ración diaria del lote', null, 39990000, 'Los 90 días del ciclo', 0),
  ('pry-9', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 9030000, 'Los 90 días del ciclo', 1),
  ('pry-9', 'Corral', 'Alquiler del corral y servicios', null, 10320000, 'Los 90 días del ciclo', 2),
  ('pry-9', 'Flete', 'Traslados del ciclo', null, 5160000, 'Los 90 días del ciclo', 3),
  ('pry-10', 'Alimentación', 'Ración diaria del lote', null, 44268000, 'Los 115 días del ciclo', 0),
  ('pry-10', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 9996000, 'Los 115 días del ciclo', 1),
  ('pry-10', 'Corral', 'Alquiler del corral y servicios', null, 11424000, 'Los 115 días del ciclo', 2),
  ('pry-10', 'Flete', 'Traslados del ciclo', null, 5712000, 'Los 115 días del ciclo', 3),
  ('pry-11', 'Alimentación', 'Ración diaria del lote', null, 24366000, 'Los 130 días del ciclo', 0),
  ('pry-11', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 5502000, 'Los 130 días del ciclo', 1),
  ('pry-11', 'Corral', 'Alquiler del corral y servicios', null, 6288000, 'Los 130 días del ciclo', 2),
  ('pry-11', 'Flete', 'Traslados del ciclo', null, 3144000, 'Los 130 días del ciclo', 3),
  ('pry-12', 'Alimentación', 'Ración diaria del lote', null, 15810000, 'Los 105 días del ciclo', 0),
  ('pry-12', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 3570000, 'Los 105 días del ciclo', 1),
  ('pry-12', 'Corral', 'Alquiler del corral y servicios', null, 4080000, 'Los 105 días del ciclo', 2),
  ('pry-12', 'Flete', 'Traslados del ciclo', null, 2040000, 'Los 105 días del ciclo', 3),
  ('pry-13', 'Alimentación', 'Ración diaria del lote', null, 38595000, 'Los 135 días del ciclo', 0),
  ('pry-13', 'Sanidad', 'Plan sanitario y mano de obra veterinaria', null, 8715000, 'Los 135 días del ciclo', 1),
  ('pry-13', 'Corral', 'Alquiler del corral y servicios', null, 9960000, 'Los 135 días del ciclo', 2),
  ('pry-13', 'Flete', 'Traslados del ciclo', null, 4980000, 'Los 135 días del ciclo', 3);

insert into cronograma_hitos (proyecto_id, hito, momento, monto_ars, condicion, orden) values
  ('pry-1', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 34740000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-1', 'Segundo tramo', 'A los 40 días', 30397500, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-1', 'Tramo final', 'A los 80 días', 21712500, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-2', 'Compra de la hacienda', 'Al alcanzar el mínimo de inicio', 79152000, 'Operación aprobada, con vendedor, precio y establecimiento receptor identificados. Se paga al vendedor.', 0),
  ('pry-2', 'Recepción del lote', 'Dentro de los 10 días de la compra', 13968000, 'DT-e cerrado en destino, inventario e identificación del lote.', 1),
  ('pry-2', 'Ración y sanidad', 'Por período, contra presupuesto', 23280000, 'Factura, remito conformado y pago al proveedor.', 2),
  ('pry-3', 'Compra de la hacienda', 'Al alcanzar el mínimo de inicio', 44268000, 'Operación aprobada, con vendedor, precio y establecimiento receptor identificados. Se paga al vendedor.', 0),
  ('pry-3', 'Recepción del lote', 'Dentro de los 10 días de la compra', 7812000, 'DT-e cerrado en destino, inventario e identificación del lote.', 1),
  ('pry-3', 'Ración y sanidad', 'Por período, contra presupuesto', 13020000, 'Factura, remito conformado y pago al proveedor.', 2),
  ('pry-4', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 39720000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-4', 'Segundo tramo', 'A los 40 días', 34755000, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-4', 'Tramo final', 'A los 80 días', 24825000, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-5', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 19680000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-5', 'Segundo tramo', 'A los 30 días', 17220000, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-5', 'Tramo final', 'A los 60 días', 12300000, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-6', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 5400000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-6', 'Segundo tramo', 'A los 37 días', 4725000, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-6', 'Tramo final', 'A los 73 días', 3375000, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-7', 'Compra de la hacienda', 'Al alcanzar el mínimo de inicio', 20298000, 'Operación aprobada, con vendedor, precio y establecimiento receptor identificados. Se paga al vendedor.', 0),
  ('pry-7', 'Recepción del lote', 'Dentro de los 10 días de la compra', 3582000, 'DT-e cerrado en destino, inventario e identificación del lote.', 1),
  ('pry-7', 'Ración y sanidad', 'Por período, contra presupuesto', 5970000, 'Factura, remito conformado y pago al proveedor.', 2),
  ('pry-14', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 22800000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-14', 'Segundo tramo', 'A los 47 días', 19950000, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-14', 'Tramo final', 'A los 93 días', 14250000, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-9', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 25800000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-9', 'Segundo tramo', 'A los 30 días', 22575000, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-9', 'Tramo final', 'A los 60 días', 16125000, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-10', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 28560000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-10', 'Segundo tramo', 'A los 38 días', 24990000, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-10', 'Tramo final', 'A los 77 días', 17850000, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-11', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 15720000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-11', 'Segundo tramo', 'A los 43 días', 13755000, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-11', 'Tramo final', 'A los 87 días', 9825000, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-12', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 10200000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-12', 'Segundo tramo', 'A los 35 días', 8925000, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-12', 'Tramo final', 'A los 70 días', 6375000, 'Rendición al día y pesada del lote cargada.', 2),
  ('pry-13', 'Primer tramo', 'Al alcanzar el mínimo de inicio', 24900000, 'Existencia del lote comprobada y presupuesto aprobado.', 0),
  ('pry-13', 'Segundo tramo', 'A los 45 días', 21787500, 'Rendición del tramo anterior: facturas, entregas y pagos.', 1),
  ('pry-13', 'Tramo final', 'A los 90 días', 15562500, 'Rendición al día y pesada del lote cargada.', 2);

insert into controles (proyecto_id, control, fecha, alcance, metodo, responsable, orden) values
  ('pry-1', 'Legajo del productor', '2026-08-21', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-1', 'Consistencia del lote', '2026-08-21', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-1', 'Autenticidad del DT-e', '2026-08-21', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2),
  ('pry-2', 'Legajo del productor', '2026-09-09', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-2', 'Consistencia del lote', '2026-09-09', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-2', 'Autenticidad del DT-e', '2026-09-09', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2),
  ('pry-3', 'Legajo del productor', '2026-08-04', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-3', 'Consistencia del lote', '2026-08-04', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-3', 'Autenticidad del DT-e', '2026-08-04', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2),
  ('pry-6', 'Legajo del productor', '2026-06-04', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-6', 'Consistencia del lote', '2026-06-04', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-6', 'Autenticidad del DT-e', '2026-06-04', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2),
  ('pry-9', 'Legajo del productor', '2026-07-09', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-9', 'Consistencia del lote', '2026-07-09', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-9', 'Autenticidad del DT-e', '2026-07-09', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2),
  ('pry-10', 'Legajo del productor', '2026-01-23', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-10', 'Consistencia del lote', '2026-01-23', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-10', 'Autenticidad del DT-e', '2026-01-23', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2),
  ('pry-11', 'Legajo del productor', '2025-07-11', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-11', 'Consistencia del lote', '2025-07-11', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-11', 'Autenticidad del DT-e', '2025-07-11', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2),
  ('pry-12', 'Legajo del productor', '2025-02-18', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-12', 'Consistencia del lote', '2025-02-18', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-12', 'Autenticidad del DT-e', '2025-02-18', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2),
  ('pry-13', 'Legajo del productor', '2026-09-20', 'Identidad, constancia de RENSPA y disponibilidad del establecimiento', 'Revisión documental', 'Equipo de validación de Guardian', 0),
  ('pry-13', 'Consistencia del lote', '2026-09-20', 'Cabezas declaradas contra las amparadas en la documentación', 'Lectura automática más reglas de control', 'Plataforma', 1),
  ('pry-13', 'Autenticidad del DT-e', '2026-09-20', 'Contraste del CUVE contra SENASA', 'Consulta por canal habilitado', 'Equipo de validación de Guardian', 2);

insert into fideicomisos (proyecto_id, serie, fiduciario, fiduciantes, fideicomisarios, bienes_fideicomitidos, objeto, reparto_resultado, mortandad, inicio_at, extincion_at, rendicion_cuentas, seguro_responsabilidad_civil, inscripcion) values
  ('pry-1', 'Guardian Ganadero — Serie I', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital, y TROPA AGROGANADERA S.A., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', '180 novillitos identificados con caravana RFID bajo el RENSPA 01.036.0.01532/04, y el capital suscripto por los colaboradores', 'Engordar el lote durante el ciclo, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 65 % para los colaboradores y 35 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2026-08-21', '2027-02-17', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada, con cobertura de mortandad sobre el lote', 'Registro Público de Comercio de la Provincia de Buenos Aires'),
  ('pry-2', 'Guardian Ganadero — Serie II', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital, y LA REDENCIÓN S.R.L., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', '220 terneros identificados con caravana RFID bajo el RENSPA 02.017.0.00841/11, y el capital suscripto por los colaboradores', 'Engordar el lote durante el ciclo, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 65 % para los colaboradores y 35 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2026-09-09', '2027-05-07', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada, con cobertura de mortandad sobre el lote', 'Registro Público de la Provincia de Córdoba'),
  ('pry-3', 'Guardian Ganadero — Serie III', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital, y GANADERA EL AMANECER S.A., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', '140 vaquillonas identificados con caravana RFID bajo el RENSPA 03.084.0.02219/07, y el capital suscripto por los colaboradores', 'Engordar el lote durante el ciclo, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 65 % para los colaboradores y 35 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2026-08-04', '2027-03-02', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada la responsabilidad civil obligatoria; sin cobertura de mortandad', 'Registro Público de Comercio de Santa Fe'),
  ('pry-6', 'Guardian Ganadero — Serie IV', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital, y TROPA AGROGANADERA S.A., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', '28 vaquillona / novillitos identificados con caravana RFID bajo el RENSPA 01.036.0.01532/04, y el capital suscripto por los colaboradores', 'Engordar el lote durante el ciclo, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 65 % para los colaboradores y 35 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2026-06-04', '2026-11-21', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada, con cobertura de mortandad sobre el lote', 'Registro Público de Comercio de la Provincia de Buenos Aires'),
  ('pry-9', 'Guardian Ganadero — Serie V', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital, y TROPA AGROGANADERA S.A., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', '120 novillos identificados con caravana RFID bajo el RENSPA 01.036.0.01532/04, y el capital suscripto por los colaboradores', 'Engordar el lote durante el ciclo, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 65 % para los colaboradores y 35 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2026-07-09', '2026-12-06', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada, con cobertura de mortandad sobre el lote', 'Registro Público de Comercio de la Provincia de Buenos Aires'),
  ('pry-10', 'Guardian Ganadero — Serie VI', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital, y TROPA AGROGANADERA S.A., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', '150 novillitos identificados con caravana RFID bajo el RENSPA 01.036.0.01532/04, y el capital suscripto por los colaboradores', 'Engordar el lote durante el ciclo, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 65 % para los colaboradores y 35 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2026-01-23', '2026-07-17', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada, con cobertura de mortandad sobre el lote', 'Registro Público de Comercio de la Provincia de Buenos Aires'),
  ('pry-11', 'Guardian Ganadero — Serie VII', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital, y TROPA AGROGANADERA S.A., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', '95 vaquillonas identificados con caravana RFID bajo el RENSPA 01.036.0.01532/04, y el capital suscripto por los colaboradores', 'Engordar el lote durante el ciclo, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 65 % para los colaboradores y 35 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2025-07-11', '2026-01-17', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada, con cobertura de mortandad sobre el lote', 'Registro Público de Comercio de la Provincia de Buenos Aires'),
  ('pry-12', 'Guardian Ganadero — Serie VIII', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital, y TROPA AGROGANADERA S.A., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', '60 novillitos identificados con caravana RFID bajo el RENSPA 01.036.0.01532/04, y el capital suscripto por los colaboradores', 'Engordar el lote durante el ciclo, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 65 % para los colaboradores y 35 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2025-02-18', '2025-08-02', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada, con cobertura de mortandad sobre el lote', 'Registro Público de Comercio de la Provincia de Buenos Aires'),
  ('pry-13', 'Guardian Ganadero — Serie IX', 'Guardian S.A.S., fiduciario de la serie', 'Los colaboradores del proyecto, que aportan el capital para los insumos, y TROPA AGROGANADERA S.A., que aporta la hacienda, el campo y el trabajo', 'Los mismos colaboradores, en proporción a lo suscripto, y el productor por su porción del resultado', 'El capital suscripto por los colaboradores y los 210 novillitos identificados con caravana RFID bajo el RENSPA 01.036.0.01532/04, afectados al fideicomiso como garantía del ciclo', 'Financiar los insumos del encierre, engordar el lote, venderlo a faena y repartir el producido entre los fideicomisarios', 'El resultado de la venta se reparte 60 % para los colaboradores y 40 % para el productor, sobre los kilos ganados en el ciclo', 'Hasta el 2 % de mortandad la absorbe el fideicomiso; por encima de ese piso responde el productor, salvo caso fortuito acreditado', '2026-09-20', '2027-04-03', 'Trimestral, y en todos los casos al cierre del ciclo', 'Contratada la responsabilidad civil obligatoria; sin cobertura de mortandad', 'Registro Público de Comercio de la Provincia de Buenos Aires');

insert into seguimiento (id, proyecto_id, fecha, cabezas, peso_promedio_kg, mortandad, gasto_ars, concepto_gasto, nota) values
  ('seg-9-1', 'pry-9', '2026-07-23', 120, 325, 0, 10033333, 'Ración y mano de obra', null),
  ('seg-9-2', 'pry-9', '2026-08-06', 120, 343, 0, 10033333, 'Ración y mano de obra', null),
  ('seg-9-3', 'pry-9', '2026-08-20', 119, 362, 1, 10033333, 'Ración, sanidad y mano de obra', 'Una baja en el lote. Se dio aviso y queda dentro del margen que absorbe el fideicomiso.'),
  ('seg-9-4', 'pry-9', '2026-09-03', 119, 382, 0, 10033333, 'Ración y mano de obra', null),
  ('seg-9-5', 'pry-9', '2026-09-17', 119, 405, 0, 10033333, 'Ración y mano de obra', null),
  ('seg-6-1', 'pry-6', '2026-06-25', 28, 253, 0, 2577273, 'Ración y mano de obra', null),
  ('seg-6-2', 'pry-6', '2026-07-16', 28, 268, 0, 2577273, 'Ración y mano de obra', null),
  ('seg-6-3', 'pry-6', '2026-08-06', 27, 285, 1, 2577273, 'Ración, sanidad y mano de obra', 'Una baja en el lote. Se dio aviso y queda dentro del margen que absorbe el fideicomiso.'),
  ('seg-6-4', 'pry-6', '2026-08-27', 27, 304, 0, 2577273, 'Ración y mano de obra', null),
  ('seg-6-5', 'pry-6', '2026-09-17', 27, 325, 0, 2577273, 'Ración y mano de obra', null),
  ('seg-10-1', 'pry-10', '2026-02-13', 150, 264, 0, 12925862, 'Ración y mano de obra', null),
  ('seg-10-2', 'pry-10', '2026-03-06', 150, 286, 0, 12925862, 'Ración y mano de obra', null),
  ('seg-10-3', 'pry-10', '2026-03-27', 149, 310, 1, 12925862, 'Ración, sanidad y mano de obra', 'Una baja en el lote. Se dio aviso y queda dentro del margen que absorbe el fideicomiso.'),
  ('seg-10-4', 'pry-10', '2026-04-17', 149, 337, 0, 12925862, 'Ración y mano de obra', null),
  ('seg-10-5', 'pry-10', '2026-05-08', 149, 367, 0, 12925862, 'Ración y mano de obra', null),
  ('seg-11-1', 'pry-11', '2025-08-01', 95, 213, 0, 5895000, 'Ración y mano de obra', null),
  ('seg-11-2', 'pry-11', '2025-08-22', 95, 228, 0, 5895000, 'Ración y mano de obra', null),
  ('seg-11-3', 'pry-11', '2025-09-12', 94, 245, 1, 5895000, 'Ración, sanidad y mano de obra', 'Una baja en el lote. Se dio aviso y queda dentro del margen que absorbe el fideicomiso.'),
  ('seg-11-4', 'pry-11', '2025-10-03', 94, 262, 0, 5895000, 'Ración y mano de obra', null),
  ('seg-11-5', 'pry-11', '2025-10-24', 94, 282, 0, 5895000, 'Ración y mano de obra', null),
  ('seg-11-6', 'pry-11', '2025-11-14', 94, 302, 0, 5895000, 'Ración, sanidad y mano de obra', null),
  ('seg-12-1', 'pry-12', '2025-03-11', 60, 266, 0, 5100000, 'Ración y mano de obra', null),
  ('seg-12-2', 'pry-12', '2025-04-01', 60, 278, 0, 5100000, 'Ración y mano de obra', null),
  ('seg-12-3', 'pry-12', '2025-04-22', 59, 291, 1, 5100000, 'Ración, sanidad y mano de obra', 'Una baja en el lote. Se dio aviso y queda dentro del margen que absorbe el fideicomiso.'),
  ('seg-12-4', 'pry-12', '2025-05-13', 59, 306, 0, 5100000, 'Ración y mano de obra', null),
  ('seg-12-5', 'pry-12', '2025-06-03', 59, 323, 0, 5100000, 'Ración y mano de obra', null);

insert into documentos (id, proyecto_id, productor_id, tipo, nombre_archivo, tiene_capa_texto, subido_at, estado_extraccion, estado_consistencia, estado_autenticidad, cuve, controles_aritmeticos, observacion_admin) values
  ('doc-1', 'pry-4', 'prod-1', 'dte', 'DT-e 032636337-5.pdf', true, '2026-09-18', 'ok', 'con_discrepancias', 'sin_verificar', '023 2636 3375', '[]'::jsonb, null),
  ('doc-2', null, 'prod-1', 'renspa', 'constancia-renspa.pdf', true, '2026-09-18', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-3', 'pry-4', 'prod-1', 'listado_rfid', 'caravanas-lote-sept.pdf', false, '2026-09-19', 'ok', 'con_discrepancias', 'sin_verificar', null, '[]'::jsonb, null),
  ('doc-4', 'pry-6', 'prod-1', 'romaneo', '708.pdf', true, '2026-09-21', 'ok', 'consistente', 'verificada', null, '[{"etiqueta":"Kilos vivos ÷ cabezas","calculado":"330,0 kg","impreso":"330 kg","coincide":true},{"etiqueta":"Kg carne ÷ kilos vivos","calculado":"58,84 %","impreso":"58,84 %","coincide":true},{"etiqueta":"Correlativo de reses (116 a 143)","calculado":"28 reses","impreso":"28 cabezas","coincide":true},{"etiqueta":"Tabla de tipificación (56 medias ÷ 2)","calculado":"28 animales","impreso":"28 cabezas","coincide":true}]'::jsonb, null),
  ('doc-5', 'pry-5', 'prod-2', 'dte', '20260921224918501_0001.pdf', false, '2026-09-20', 'procesando', 'sin_revisar', 'sin_verificar', null, '[]'::jsonb, null),
  ('doc-6', 'pry-5', 'prod-2', 'poliza_seguro', 'poliza-mortandad-2026.pdf', true, '2026-09-20', 'ok', 'consistente', 'sin_verificar', null, '[]'::jsonb, null),
  ('doc-7', 'pry-1', 'prod-1', 'dte', 'DT-e ingreso-invernada.pdf', true, '2026-08-14', 'ok', 'consistente', 'verificada', '021 8845 1120', '[]'::jsonb, null),
  ('doc-8', null, 'prod-2', 'renspa', 'constancia-renspa-la-redencion.pdf', true, '2026-07-30', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-9', null, 'prod-3', 'renspa', 'constancia-renspa-el-amanecer.pdf', true, '2026-08-05', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-r1', 'pry-1', 'prod-1', 'listado_rfid', 'caravanas pry-1.csv', true, '2026-08-21', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-r11', 'pry-2', 'prod-2', 'boleto_compraventa', 'boleto compra pry-2.pdf', true, '2026-09-09', 'ok', 'consistente', 'sin_verificar', null, '[]'::jsonb, null),
  ('doc-r21', 'pry-3', 'prod-3', 'dte', 'DT-e ingreso pry-3.pdf', true, '2026-08-04', 'ok', 'consistente', 'verificada', '023 4121 3303', '[]'::jsonb, null),
  ('doc-r22', 'pry-3', 'prod-3', 'listado_rfid', 'caravanas pry-3.csv', true, '2026-08-04', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-r23', 'pry-3', 'prod-3', 'boleto_compraventa', 'boleto compra pry-3.pdf', true, '2026-08-04', 'ok', 'consistente', 'sin_verificar', null, '[]'::jsonb, null),
  ('doc-r31', 'pry-6', 'prod-1', 'dte', 'DT-e ingreso pry-6.pdf', true, '2026-06-04', 'ok', 'consistente', 'verificada', '026 4142 3306', '[]'::jsonb, null),
  ('doc-r32', 'pry-6', 'prod-1', 'listado_rfid', 'caravanas pry-6.csv', true, '2026-06-04', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-r41', 'pry-9', 'prod-1', 'dte', 'DT-e ingreso pry-9.pdf', true, '2026-07-09', 'ok', 'consistente', 'verificada', '029 4163 3309', '[]'::jsonb, null),
  ('doc-r42', 'pry-9', 'prod-1', 'listado_rfid', 'caravanas pry-9.csv', true, '2026-07-09', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-r51', 'pry-10', 'prod-1', 'dte', 'DT-e ingreso pry-10.pdf', true, '2026-01-23', 'ok', 'consistente', 'verificada', '030 4170 3310', '[]'::jsonb, null),
  ('doc-r52', 'pry-10', 'prod-1', 'listado_rfid', 'caravanas pry-10.csv', true, '2026-01-23', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-r53', 'pry-10', 'prod-1', 'romaneo', 'romaneo 31488207.pdf', true, '2026-05-19', 'ok', 'consistente', 'verificada', null, '[{"etiqueta":"Kilos vivos ÷ cabezas","calculado":"383 kg","impreso":"383 kg","coincide":true},{"etiqueta":"Kg de carne ÷ kilos vivos","calculado":"57.82 %","impreso":"57.82 %","coincide":true}]'::jsonb, null),
  ('doc-r61', 'pry-11', 'prod-1', 'dte', 'DT-e ingreso pry-11.pdf', true, '2025-07-11', 'ok', 'consistente', 'verificada', '031 4177 3311', '[]'::jsonb, null),
  ('doc-r62', 'pry-11', 'prod-1', 'listado_rfid', 'caravanas pry-11.csv', true, '2025-07-11', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-r63', 'pry-11', 'prod-1', 'romaneo', 'romaneo 30117645.pdf', true, '2025-11-28', 'ok', 'consistente', 'verificada', null, '[{"etiqueta":"Kilos vivos ÷ cabezas","calculado":"317 kg","impreso":"317 kg","coincide":true},{"etiqueta":"Kg de carne ÷ kilos vivos","calculado":"57.40 %","impreso":"57.4 %","coincide":true}]'::jsonb, null),
  ('doc-r71', 'pry-12', 'prod-1', 'dte', 'DT-e ingreso pry-12.pdf', true, '2025-02-18', 'ok', 'consistente', 'verificada', '032 4184 3312', '[]'::jsonb, null),
  ('doc-r72', 'pry-12', 'prod-1', 'listado_rfid', 'caravanas pry-12.csv', true, '2025-02-18', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null),
  ('doc-r73', 'pry-12', 'prod-1', 'romaneo', 'romaneo 29004318.pdf', true, '2025-06-03', 'ok', 'consistente', 'verificada', null, '[{"etiqueta":"Kilos vivos ÷ cabezas","calculado":"323 kg","impreso":"323 kg","coincide":true},{"etiqueta":"Kg de carne ÷ kilos vivos","calculado":"57.10 %","impreso":"57.1 %","coincide":true}]'::jsonb, null),
  ('doc-r81', 'pry-13', 'prod-1', 'dte', 'DT-e ingreso pry-13.pdf', true, '2026-09-20', 'ok', 'consistente', 'verificada', '033 4191 3313', '[]'::jsonb, null),
  ('doc-r82', 'pry-13', 'prod-1', 'listado_rfid', 'caravanas pry-13.csv', true, '2026-09-20', 'ok', 'consistente', 'verificada', null, '[]'::jsonb, null);

insert into extracciones (documento_id, campo, etiqueta, valor, confianza, orden) values
  ('doc-1', 'numero', 'Nº de DT-e', '032636337-5', 0.99, 0),
  ('doc-1', 'cuve', 'CUVE', '023 2636 3375', 0.97, 1),
  ('doc-1', 'fechaCarga', 'Fecha de carga', '22/09/2026', 0.98, 2),
  ('doc-1', 'motivo', 'Motivo', 'Faena', 0.99, 3),
  ('doc-1', 'renspaOrigen', 'RENSPA origen', '01.036.0.01532/04', 0.96, 4),
  ('doc-1', 'titularOrigen', 'Titular origen', 'TROPA AGROGANADERA S.A.', 0.98, 5),
  ('doc-1', 'cuitOrigen', 'CUIT origen', '30-71903430-2', 0.99, 6),
  ('doc-1', 'establecimiento', 'Establecimiento', 'DOÑA INA', 0.94, 7),
  ('doc-1', 'destinoTipo', 'Tipo de destino', 'FRIGORÍFICO', 0.97, 8),
  ('doc-1', 'cabezas', 'Cabezas (total)', '34', 0.93, 9),
  ('doc-1', 'detalleCategorias', 'Detalle por categoría', 'Vaquillona 20 · Novillito 14', 0.91, 10),
  ('doc-1', 'ultimaAftosa', 'Última aftosa', '18/05/2026', 0.95, 11),
  ('doc-2', 'renspa', 'RENSPA', '01.036.0.01532/04', 0.98, 0),
  ('doc-2', 'titular', 'Titular', 'TROPA AGROGANADERA S.A.', 0.97, 1),
  ('doc-2', 'cuit', 'CUIT', '30-71903430-2', 0.99, 2),
  ('doc-2', 'establecimiento', 'Establecimiento', 'DOÑA INA', 0.95, 3),
  ('doc-2', 'partido', 'Partido', 'Exaltación de la Cruz', 0.93, 4),
  ('doc-3', 'cantidad', 'Identificadores leídos', '180', 0.72, 0),
  ('doc-3', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.88, 1),
  ('doc-3', 'duplicados', 'Duplicados internos', '0', 0.95, 2),
  ('doc-4', 'numero', 'Nº de romaneo', '2.537.774', 0.98, 0),
  ('doc-4', 'fecha', 'Fecha', '21/09/2026', 0.99, 1),
  ('doc-4', 'frigorifico', 'Frigorífico', 'Agroindustrias Quilmes S.A.', 0.97, 2),
  ('doc-4', 'vendedorCuit', 'CUIT vendedor', '30-71903430-2', 0.99, 3),
  ('doc-4', 'dte', 'DT-e asociado', '32624494', 0.96, 4),
  ('doc-4', 'cabezasFaena', 'Cabezas faena', '28', 0.97, 5),
  ('doc-4', 'kilosVivos', 'Kilos vivos', '9.240', 0.98, 6),
  ('doc-4', 'kgCarne', 'Kg de carne', '5.437', 0.96, 7),
  ('doc-4', 'rendimiento', 'Rendimiento', '58,84 %', 0.98, 8),
  ('doc-6', 'aseguradora', 'Aseguradora', 'Sancor Seguros', 0.96, 0),
  ('doc-6', 'numero', 'Nº de póliza', '77-0194882', 0.94, 1),
  ('doc-6', 'vigencia', 'Vigencia', '01/09/2026 — 28/02/2027', 0.92, 2),
  ('doc-6', 'sumaAsegurada', 'Suma asegurada', '$ 49.000.000', 0.9, 3),
  ('doc-6', 'riesgo', 'Riesgo cubierto', 'Mortandad por accidente y enfermedad', 0.89, 4),
  ('doc-7', 'numero', 'Nº de DT-e', '031884511-2', 0.98, 0),
  ('doc-7', 'motivo', 'Motivo', 'Invernada', 0.97, 1),
  ('doc-7', 'cabezas', 'Cabezas', '180', 0.96, 2),
  ('doc-7', 'renspaDestino', 'RENSPA destino', '01.036.0.01532/04', 0.95, 3),
  ('doc-8', 'renspa', 'RENSPA', '02.017.0.00841/11', 0.97, 0),
  ('doc-8', 'titular', 'Titular', 'LA REDENCIÓN S.R.L.', 0.96, 1),
  ('doc-8', 'cuit', 'CUIT', '30-70912844-7', 0.98, 2),
  ('doc-8', 'establecimiento', 'Establecimiento', 'LA REDENCIÓN', 0.95, 3),
  ('doc-8', 'partido', 'Partido', 'Marcos Juárez', 0.94, 4),
  ('doc-9', 'renspa', 'RENSPA', '03.084.0.02219/07', 0.98, 0),
  ('doc-9', 'titular', 'Titular', 'GANADERA EL AMANECER S.A.', 0.97, 1),
  ('doc-9', 'cuit', 'CUIT', '30-71554098-5', 0.99, 2),
  ('doc-9', 'establecimiento', 'Establecimiento', 'EL AMANECER', 0.96, 3),
  ('doc-9', 'partido', 'Partido', 'Venado Tuerto', 0.93, 4),
  ('doc-r1', 'cantidad', 'Identificadores leídos', '180', 0.94, 0),
  ('doc-r1', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.96, 1),
  ('doc-r1', 'duplicados', 'Duplicados internos', '0', 0.97, 2),
  ('doc-r11', 'vendedor', 'Vendedor', 'Consignataria del Centro S.A.', 0.95, 0),
  ('doc-r11', 'comprador', 'Comprador', 'LA REDENCIÓN S.R.L.', 0.97, 1),
  ('doc-r11', 'cantidad', 'Cantidad', '220 cabezas', 0.96, 2),
  ('doc-r11', 'categoria', 'Categoría', 'Ternero', 0.94, 3),
  ('doc-r11', 'fecha', 'Fecha del boleto', '09/09/2026', 0.98, 4),
  ('doc-r21', 'numero', 'Nº de DT-e', '031844039-3', 0.98, 0),
  ('doc-r21', 'motivo', 'Motivo', 'Invernada', 0.97, 1),
  ('doc-r21', 'cabezas', 'Cabezas', '140', 0.96, 2),
  ('doc-r21', 'renspaDestino', 'RENSPA destino', '03.084.0.02219/07', 0.95, 3),
  ('doc-r21', 'titularOrigen', 'Titular', 'GANADERA EL AMANECER S.A.', 0.97, 4),
  ('doc-r22', 'cantidad', 'Identificadores leídos', '140', 0.94, 0),
  ('doc-r22', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.96, 1),
  ('doc-r22', 'duplicados', 'Duplicados internos', '0', 0.97, 2),
  ('doc-r23', 'vendedor', 'Vendedor', 'Consignataria del Centro S.A.', 0.95, 0),
  ('doc-r23', 'comprador', 'Comprador', 'GANADERA EL AMANECER S.A.', 0.97, 1),
  ('doc-r23', 'cantidad', 'Cantidad', '140 cabezas', 0.96, 2),
  ('doc-r23', 'categoria', 'Categoría', 'Vaquillona', 0.94, 3),
  ('doc-r23', 'fecha', 'Fecha del boleto', '04/08/2026', 0.98, 4),
  ('doc-r31', 'numero', 'Nº de DT-e', '031844078-6', 0.98, 0),
  ('doc-r31', 'motivo', 'Motivo', 'Invernada', 0.97, 1),
  ('doc-r31', 'cabezas', 'Cabezas', '28', 0.96, 2),
  ('doc-r31', 'renspaDestino', 'RENSPA destino', '01.036.0.01532/04', 0.95, 3),
  ('doc-r31', 'titularOrigen', 'Titular', 'TROPA AGROGANADERA S.A.', 0.97, 4),
  ('doc-r32', 'cantidad', 'Identificadores leídos', '28', 0.94, 0),
  ('doc-r32', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.96, 1),
  ('doc-r32', 'duplicados', 'Duplicados internos', '0', 0.97, 2),
  ('doc-r41', 'numero', 'Nº de DT-e', '031844117-0', 0.98, 0),
  ('doc-r41', 'motivo', 'Motivo', 'Invernada', 0.97, 1),
  ('doc-r41', 'cabezas', 'Cabezas', '120', 0.96, 2),
  ('doc-r41', 'renspaDestino', 'RENSPA destino', '01.036.0.01532/04', 0.95, 3),
  ('doc-r41', 'titularOrigen', 'Titular', 'TROPA AGROGANADERA S.A.', 0.97, 4),
  ('doc-r42', 'cantidad', 'Identificadores leídos', '120', 0.94, 0),
  ('doc-r42', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.96, 1),
  ('doc-r42', 'duplicados', 'Duplicados internos', '0', 0.97, 2),
  ('doc-r51', 'numero', 'Nº de DT-e', '031844130-1', 0.98, 0),
  ('doc-r51', 'motivo', 'Motivo', 'Invernada', 0.97, 1),
  ('doc-r51', 'cabezas', 'Cabezas', '150', 0.96, 2),
  ('doc-r51', 'renspaDestino', 'RENSPA destino', '01.036.0.01532/04', 0.95, 3),
  ('doc-r51', 'titularOrigen', 'Titular', 'TROPA AGROGANADERA S.A.', 0.97, 4),
  ('doc-r52', 'cantidad', 'Identificadores leídos', '150', 0.94, 0),
  ('doc-r52', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.96, 1),
  ('doc-r52', 'duplicados', 'Duplicados internos', '0', 0.97, 2),
  ('doc-r53', 'dteSalida', 'Nº de DT-e', '31488207', 0.97, 0),
  ('doc-r53', 'frigorifico', 'Frigorífico', 'Frigorífico Regional del Norte S.A.', 0.95, 1),
  ('doc-r53', 'cabezasFaena', 'Cabezas faena', '150', 0.96, 2),
  ('doc-r53', 'kilosVivos', 'Kilos vivos', '57450', 0.95, 3),
  ('doc-r53', 'kgCarne', 'Kg de carne', '33218', 0.94, 4),
  ('doc-r53', 'rendimiento', 'Rendimiento', '57.82 %', 0.96, 5),
  ('doc-r61', 'numero', 'Nº de DT-e', '031844143-2', 0.98, 0),
  ('doc-r61', 'motivo', 'Motivo', 'Invernada', 0.97, 1),
  ('doc-r61', 'cabezas', 'Cabezas', '95', 0.96, 2),
  ('doc-r61', 'renspaDestino', 'RENSPA destino', '01.036.0.01532/04', 0.95, 3),
  ('doc-r61', 'titularOrigen', 'Titular', 'TROPA AGROGANADERA S.A.', 0.97, 4),
  ('doc-r62', 'cantidad', 'Identificadores leídos', '95', 0.94, 0),
  ('doc-r62', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.96, 1),
  ('doc-r62', 'duplicados', 'Duplicados internos', '0', 0.97, 2),
  ('doc-r63', 'dteSalida', 'Nº de DT-e', '30117645', 0.97, 0),
  ('doc-r63', 'frigorifico', 'Frigorífico', 'Frigorífico Regional del Norte S.A.', 0.95, 1),
  ('doc-r63', 'cabezasFaena', 'Cabezas faena', '95', 0.96, 2),
  ('doc-r63', 'kilosVivos', 'Kilos vivos', '30115', 0.95, 3),
  ('doc-r63', 'kgCarne', 'Kg de carne', '17285', 0.94, 4),
  ('doc-r63', 'rendimiento', 'Rendimiento', '57.40 %', 0.96, 5),
  ('doc-r71', 'numero', 'Nº de DT-e', '031844156-3', 0.98, 0),
  ('doc-r71', 'motivo', 'Motivo', 'Invernada', 0.97, 1),
  ('doc-r71', 'cabezas', 'Cabezas', '60', 0.96, 2),
  ('doc-r71', 'renspaDestino', 'RENSPA destino', '01.036.0.01532/04', 0.95, 3),
  ('doc-r71', 'titularOrigen', 'Titular', 'TROPA AGROGANADERA S.A.', 0.97, 4),
  ('doc-r72', 'cantidad', 'Identificadores leídos', '60', 0.94, 0),
  ('doc-r72', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.96, 1),
  ('doc-r72', 'duplicados', 'Duplicados internos', '0', 0.97, 2),
  ('doc-r73', 'dteSalida', 'Nº de DT-e', '29004318', 0.97, 0),
  ('doc-r73', 'frigorifico', 'Frigorífico', 'Frigorífico Regional del Norte S.A.', 0.95, 1),
  ('doc-r73', 'cabezasFaena', 'Cabezas faena', '60', 0.96, 2),
  ('doc-r73', 'kilosVivos', 'Kilos vivos', '19380', 0.95, 3),
  ('doc-r73', 'kgCarne', 'Kg de carne', '11066', 0.94, 4),
  ('doc-r73', 'rendimiento', 'Rendimiento', '57.10 %', 0.96, 5),
  ('doc-r81', 'numero', 'Nº de DT-e', '031844169-4', 0.98, 0),
  ('doc-r81', 'motivo', 'Motivo', 'Invernada', 0.97, 1),
  ('doc-r81', 'cabezas', 'Cabezas', '210', 0.96, 2),
  ('doc-r81', 'renspaDestino', 'RENSPA destino', '01.036.0.01532/04', 0.95, 3),
  ('doc-r81', 'titularOrigen', 'Titular', 'TROPA AGROGANADERA S.A.', 0.97, 4),
  ('doc-r82', 'cantidad', 'Identificadores leídos', '210', 0.94, 0),
  ('doc-r82', 'formato', 'Formato', 'Válido (15 dígitos, prefijo 032)', 0.96, 1),
  ('doc-r82', 'duplicados', 'Duplicados internos', '0', 0.97, 2);

insert into discrepancias (id, documento_id, campo, etiqueta, valor_declarado, valor_extraido, severidad, detalle, resuelta, resolucion) values
  ('dis-1', 'doc-1', 'cabezas', 'Cantidad de cabezas', '200', '34', 'alta', 'El proyecto declara 200 cabezas y el DT-e ampara 34 (20 vaquillonas + 14 novillitos). El documento no respalda el lote completo: falta documentación por 166 cabezas.', false, null),
  ('dis-2', 'doc-1', 'motivo', 'Motivo del movimiento', 'Ingreso al ciclo', 'Faena', 'alta', 'El DT-e es de salida a frigorífico, no de ingreso al establecimiento. Para abrir un ciclo de engorde se espera un DT-e con motivo Invernada o Traslado.', false, null),
  ('dis-3', 'doc-3', 'cantidad', 'Identificadores RFID', '200', '180', 'media', 'Se leyeron 180 identificadores sobre 200 cabezas declaradas. El archivo está escaneado sin capa de texto y la confianza de lectura es baja (72%): puede ser un faltante real o una lectura incompleta.', false, null);

insert into aportes (id, proyecto_id, colaborador_id, orden_suscripcion, monto_comprometido_ars, monto_acreditado_ars, estado, adhesion_at, contrato_version) values
  ('ap-1', 'pry-1', 'col-1', 'GDN-2026-000181', 7500000, 7500000, 'acreditado', '2026-08-23', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-2', 'pry-13', 'col-1', 'GDN-2026-000204', 6000000, 3750000, 'acreditado_parcial', '2026-09-21', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-3', 'pry-2', 'col-1', 'GDN-2026-000219', 4500000, 0, 'pendiente_acreditacion', '2026-09-26', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-4', 'pry-6', 'col-1', 'GDN-2026-000102', 3000000, 3000000, 'acreditado', '2026-06-03', 'Contrato de adhesión v2 — 2026-03-14'),
  ('ap-r1', 'pry-1', 'col-otros', 'GDN-2026-900001', 45450000, 45450000, 'acreditado', '2026-08-21', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-r2', 'pry-2', 'col-otros', 'GDN-2026-900002', 23250000, 23250000, 'acreditado', '2026-09-09', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-r3', 'pry-3', 'col-otros', 'GDN-2026-900003', 65100000, 65100000, 'acreditado', '2026-08-04', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-r4', 'pry-6', 'col-otros', 'GDN-2026-900004', 10500000, 10500000, 'acreditado', '2026-06-04', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-r5', 'pry-9', 'col-otros', 'GDN-2026-900005', 64500000, 64500000, 'acreditado', '2026-07-09', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-r6', 'pry-10', 'col-otros', 'GDN-2026-900006', 71400000, 71400000, 'acreditado', '2026-01-23', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-r7', 'pry-11', 'col-otros', 'GDN-2026-900007', 39300000, 39300000, 'acreditado', '2025-07-11', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-r8', 'pry-12', 'col-otros', 'GDN-2026-900008', 25500000, 25500000, 'acreditado', '2025-02-18', 'Contrato de adhesión v3 — 2026-08-01'),
  ('ap-r9', 'pry-13', 'col-otros', 'GDN-2026-900009', 14850000, 14850000, 'acreditado', '2026-09-20', 'Contrato de adhesión v3 — 2026-08-01');

insert into movimientos_bancarios (id, aporte_id, referencia_externa, importe_ars, fecha, estado_conciliacion, observacion) values
  ('mov-1', 'ap-1', 'TRF-9f21c4', 7500000, '2026-08-25', 'conciliado', null),
  ('mov-2', 'ap-2', 'TRF-4b88a1', 3750000, '2026-09-22', 'con_diferencia', 'Se acreditaron $ 3.750.000 contra una orden de $ 6.000.000. Queda pendiente el resto: la diferencia no se completa sola.'),
  ('mov-3', 'ap-4', 'TRF-1a77d0', 3000000, '2026-06-04', 'conciliado', null),
  ('mov-r1', 'ap-r1', 'TRF-pry-1', 45450000, '2026-08-21', 'conciliado', null),
  ('mov-r2', 'ap-r2', 'TRF-pry-2', 23250000, '2026-09-09', 'conciliado', null),
  ('mov-r3', 'ap-r3', 'TRF-pry-3', 65100000, '2026-08-04', 'conciliado', null),
  ('mov-r4', 'ap-r4', 'TRF-pry-6', 10500000, '2026-06-04', 'conciliado', null),
  ('mov-r5', 'ap-r5', 'TRF-pry-9', 64500000, '2026-07-09', 'conciliado', null),
  ('mov-r6', 'ap-r6', 'TRF-pry-10', 71400000, '2026-01-23', 'conciliado', null),
  ('mov-r7', 'ap-r7', 'TRF-pry-11', 39300000, '2025-07-11', 'conciliado', null),
  ('mov-r8', 'ap-r8', 'TRF-pry-12', 25500000, '2025-02-18', 'conciliado', null),
  ('mov-r9', 'ap-r9', 'TRF-pry-13', 14850000, '2026-09-20', 'conciliado', null);

insert into liquidaciones (id, proyecto_id, colaborador_id, concepto, capital_ars, resultado_ars, estado, fecha, pagada_at) values
  ('liq-1', 'pry-6', 'col-1', 'Cierre del ciclo, con el resultado de la venta ya cobrada', 3000000, 730500, 'pagada', '2026-09-19', '2026-09-23');
